-- Document current invoice_number format (RE-YYYY-MM-NNNN).
-- Do not edit historical migrations; apply comment updates in new files only.

COMMENT ON COLUMN public.invoices.invoice_number IS
$$Human-readable invoice number. Format: RE-YYYY-MM-NNNN (e.g. RE-2026-04-0001).
Sequence resets each calendar month; month/year are taken from the date at generation (create / Storno insert).

Generated by: src/features/invoices/lib/invoice-number.ts.

Stornorechnungen receive a new number in the same RE-YYYY-MM-NNNN format (not a separate STORNO- prefix).$$;
