-- ============================================================
-- Migration: create_invoices
--
-- Creates the invoices table. Each row is one invoice issued
-- by the Taxi company to one Payer (Kostenträger) for one
-- billing period.
--
-- Status machine:
--   draft ──→ sent ──→ paid
--               └──→ cancelled  (auto-creates a Stornorechnung
--                                via cancels_invoice_id FK)
--
-- Invoice numbers follow the format RE-YYYY-NNNN
-- (e.g. RE-2026-0001). Numbers are globally sequential and
-- uninterrupted as required by §14 UStG.
--
-- Linked to:
--   companies     → company_id   (multi-tenant isolation)
--   payers        → payer_id     (Leistungsempfänger)
--   billing_types → billing_type_id (optional type filter)
--   clients       → client_id    (per_client mode only)
--   invoices      → cancels_invoice_id (Storno chain, self-ref)
--
-- Run once in: Supabase Dashboard → SQL Editor → Run
-- ============================================================

CREATE TABLE IF NOT EXISTS public.invoices (

  -- ── Identity ──────────────────────────────────────────────
  id                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Multi-tenant scope: every invoice belongs to one Taxi company.
  -- Type must be UUID to match companies.id (not TEXT).
  company_id            UUID          NOT NULL
                          REFERENCES public.companies(id),

  -- Human-readable invoice number. Format: RE-YYYY-NNNN.
  -- Must be globally unique and uninterrupted (§14 UStG fortlaufende Nummer).
  -- Generated by: src/features/invoices/lib/invoice-number.ts
  invoice_number        TEXT          NOT NULL UNIQUE,

  -- ── Recipient ─────────────────────────────────────────────
  -- The Payer (Kostenträger) this invoice is issued to.
  -- Address snapshot for the recipient block is read from payers at PDF time.
  payer_id              UUID          NOT NULL
                          REFERENCES public.payers(id),

  -- Optional filter to one billing family (Abrechnungsfamilie) within the payer.
  -- NULL means "all billing types for this payer are included".
  billing_type_id       UUID
                          REFERENCES public.billing_types(id),

  -- ── Billing Mode ──────────────────────────────────────────
  -- Controls which trips are included and how the invoice is presented.
  --   monthly      → all trips for this payer in the given period
  --   single_trip  → one specific trip (referenced in invoice_line_items)
  --   per_client   → all trips for one Fahrgast (client_id required)
  mode                  TEXT          NOT NULL
                          CHECK (mode IN ('monthly', 'single_trip', 'per_client')),

  -- FK to a specific Fahrgast (client). Only populated when mode = 'per_client'.
  -- In per_client mode the client is the invoice recipient (not the payer).
  client_id             UUID
                          REFERENCES public.clients(id),

  -- ── Billing Period ────────────────────────────────────────
  -- Date range (inclusive) for which trips are included on this invoice.
  -- For monthly mode: first and last day of the selected month.
  -- For single_trip:  both set to the trip's date.
  period_from           DATE          NOT NULL,
  period_to             DATE          NOT NULL,

  -- ── Status Machine ────────────────────────────────────────
  -- Allowed transitions:
  --   draft      → sent        (Rechnung versenden)
  --   sent       → paid        (Zahlung eingegangen)
  --   sent       → cancelled   (Stornierung — triggers Stornorechnung creation)
  --   cancelled  → (terminal)
  --   corrected  → (terminal, set on original invoice when replaced by Storno)
  status                TEXT          NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft','sent','paid','cancelled','corrected')),

  -- ── Financial Totals (Immutable Snapshot) ─────────────────
  -- Calculated once when the invoice is finalized (status: draft → sent).
  -- Do NOT update these retroactively — invoices are legal documents.
  -- If amounts must change, cancel and issue a corrected invoice.
  subtotal              NUMERIC(10,2) NOT NULL DEFAULT 0, -- Nettobetrag (before tax)
  tax_amount            NUMERIC(10,2) NOT NULL DEFAULT 0, -- Steuerbetrag (total MwSt)
  total                 NUMERIC(10,2) NOT NULL DEFAULT 0, -- Bruttobetrag (final amount)

  -- ── Invoice Configuration ─────────────────────────────────
  -- Optional free-text note printed in the invoice body.
  -- Example: "Gemäß Vertrag Nr. 1234 vom 01.01.2026".
  notes                 TEXT,

  -- Days from invoice date until payment is due (Zahlungsziel).
  -- Default copied from company_profiles.default_payment_days on invoice creation.
  -- Can be overridden per invoice in Step 4 of the invoice builder.
  payment_due_days      INTEGER       NOT NULL DEFAULT 14,

  -- ── Audit Fields ──────────────────────────────────────────
  -- Supabase user ID (auth.uid()) of the admin who created this invoice.
  created_by            TEXT,
  created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
  -- Set to now() on every update (status changes, edits to draft).
  updated_at            TIMESTAMPTZ,

  -- Lifecycle timestamps (set when the corresponding status transition occurs)
  sent_at               TIMESTAMPTZ,      -- Set when status → 'sent'
  paid_at               TIMESTAMPTZ,      -- Set when status → 'paid'
  cancelled_at          TIMESTAMPTZ,      -- Set when status → 'cancelled'

  -- ── Storno Chain ──────────────────────────────────────────
  -- When an invoice is storniert (cancelled), the system auto-creates
  -- a new Stornorechnung with negative line item amounts.
  -- This FK on the Stornorechnung points to the original invoice it cancels.
  -- NULL on all normal (non-storno) invoices.
  --
  -- To find the Stornorechnung for invoice X:
  --   SELECT * FROM invoices WHERE cancels_invoice_id = X.id
  cancels_invoice_id    UUID
                          REFERENCES public.invoices(id)
);

-- ── Indexes ───────────────────────────────────────────────────
-- Optimized for the most common query patterns in the invoice list.

-- Filter / group by company (every query includes this)
CREATE INDEX IF NOT EXISTS idx_invoices_company_id
  ON public.invoices (company_id);

-- Filter by payer (most common second filter)
CREATE INDEX IF NOT EXISTS idx_invoices_payer_id
  ON public.invoices (payer_id);

-- Filter by status (tabs: Entwürfe / Versendet / Bezahlt / Alle)
CREATE INDEX IF NOT EXISTS idx_invoices_status
  ON public.invoices (status);

-- Sort by date / filter by period
CREATE INDEX IF NOT EXISTS idx_invoices_created_at
  ON public.invoices (created_at);

CREATE INDEX IF NOT EXISTS idx_invoices_period
  ON public.invoices (period_from, period_to);


-- ════════════════════════════════════════════════════════════
-- Column comments — TABLE: invoices
-- ════════════════════════════════════════════════════════════

COMMENT ON TABLE public.invoices IS
$$One row per invoice issued by the Taxi company to a Payer.
Covers three billing modes: monthly runs, single trips, or
per-Fahrgast billing. Follows the German invoice status lifecycle:
  draft → sent → paid | cancelled (Storno)

Financial totals are stored as an immutable snapshot at the time
of finalization. All detail rows live in invoice_line_items.$$;

COMMENT ON COLUMN public.invoices.id IS
$$Primary key (UUID). Auto-generated on insert.$$;

COMMENT ON COLUMN public.invoices.company_id IS
$$FK → companies.id (UUID). Used for multi-tenant data isolation.
Every query on invoices must filter by company_id to ensure
one company cannot access another company's invoices.
Type is UUID (not TEXT) — must match companies.id exactly.$$;

COMMENT ON COLUMN public.invoices.invoice_number IS
$$Human-readable invoice number. Format: RE-YYYY-NNNN (e.g. RE-2026-0001).
Must be globally unique and uninterrupted (§14 UStG).
Generated by: src/features/invoices/lib/invoice-number.ts.
For Stornorechungen the format is: STORNO-RE-YYYY-NNNN.$$;

COMMENT ON COLUMN public.invoices.payer_id IS
$$FK → payers.id. The Kostenträger (Leistungsempfänger) this
invoice is issued to. Payer address for the invoice PDF is read
from payers.street / city etc. at PDF render time (not snapshotted).$$;

COMMENT ON COLUMN public.invoices.billing_type_id IS
$$FK → billing_types.id. Optional filter to one billing family
(Abrechnungsfamilie) within the payer.
NULL = all billing types for this payer are included in the invoice.$$;

COMMENT ON COLUMN public.invoices.mode IS
$$Billing mode. Controls which trips are collected:
  monthly     → all trips for the payer in period_from..period_to
  single_trip → exactly one trip (referenced in invoice_line_items.trip_id)
  per_client  → all trips for one Fahrgast in the period (client_id required)

Allowed values enforced by CHECK constraint.$$;

COMMENT ON COLUMN public.invoices.client_id IS
$$FK → clients.id. The specific Fahrgast for per_client billing mode.
In this mode the client is the invoice recipient (not the payer).
NULL for monthly and single_trip modes.$$;

COMMENT ON COLUMN public.invoices.period_from IS
$$Start date (inclusive) of the billing period.
For monthly: first day of the month. For single_trip: the trip date.$$;

COMMENT ON COLUMN public.invoices.period_to IS
$$End date (inclusive) of the billing period.
For monthly: last day of the month. For single_trip: the trip date.$$;

COMMENT ON COLUMN public.invoices.status IS
$$Current lifecycle status. Allowed values (enforced by CHECK constraint):
  draft      – being prepared, can still be edited
  sent       – sent to the payer, amounts locked
  paid       – payment received
  cancelled  – storniert; a Stornorechnung was auto-created
  corrected  – set on the original invoice when it has been replaced by a Storno

Transitions:
  draft → sent → paid
  sent  → cancelled  (auto-creates Stornorechnung)$$;

COMMENT ON COLUMN public.invoices.subtotal IS
$$Nettobetrag — total before tax. Immutable snapshot, set when invoice is finalized.
Sum of all invoice_line_items.total_price.$$;

COMMENT ON COLUMN public.invoices.tax_amount IS
$$Total MwSt (Steuerbetrag). Immutable snapshot.
May include both 7% and 19% portions (see invoice_line_items.tax_rate).$$;

COMMENT ON COLUMN public.invoices.total IS
$$Bruttobetrag (Endbetrag) — subtotal + tax_amount. Immutable snapshot.$$;

COMMENT ON COLUMN public.invoices.notes IS
$$Optional free-text note printed in the invoice body.
Example: "Gemäß Rahmenvertrag Nr. 1234 vom 01.01.2026".$$;

COMMENT ON COLUMN public.invoices.payment_due_days IS
$$Days from invoice date until payment is due (Zahlungsziel).
Copied from company_profiles.default_payment_days on creation.
Editable per invoice in the invoice builder.$$;

COMMENT ON COLUMN public.invoices.created_by IS
$$auth.uid() of the admin who created this invoice.
For audit trail: traces invoice creation back to a specific user.$$;

COMMENT ON COLUMN public.invoices.created_at IS
$$Timestamp (UTC) when the invoice was first created (as draft).$$;

COMMENT ON COLUMN public.invoices.updated_at IS
$$Timestamp (UTC) of the last modification (status change or draft edit).$$;

COMMENT ON COLUMN public.invoices.sent_at IS
$$Timestamp (UTC) when the invoice was marked as sent. NULL if draft.$$;

COMMENT ON COLUMN public.invoices.paid_at IS
$$Timestamp (UTC) when payment was received. NULL if not yet paid.$$;

COMMENT ON COLUMN public.invoices.cancelled_at IS
$$Timestamp (UTC) when the invoice was storniert. NULL if not cancelled.$$;

COMMENT ON COLUMN public.invoices.cancels_invoice_id IS
$$Self-referencing FK → invoices.id.
Set on a Stornorechnung to point to the original invoice it cancels.
NULL on all normal invoices.

To find the Stornorechnung for an invoice:
  SELECT * FROM invoices WHERE cancels_invoice_id = '<original_id>';$$;
